- name: cart
  hosts: cart
  become: yes
  tasks: 
   - name: disable old nodejs and enable nodejs
     ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

   - name: Install nodejs # ansible install nodejs module
     ansible.builtin.dnf:
      name: nodejs
      state: present

   - name: Add cart roboshop # ansible adduseer module
     ansible.builtin.user:
      name: roboshop 

   - name: Recursively remove app directory # ansible app directory
     ansible.builtin.file:
      path: /app
      state: absent 

   - name: create app directory # ansible app directory
     ansible.builtin.file:
      path: /app
      state: directory     

   - name: Download for cart application # ansible download module
     ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

   - name: extract cart application # ansible unarchive module
     ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes 

   - name: Install npm 
     community.general.npm:
      name: npm
      path: /app


   - name: Copy cart service # ansible copy module
     ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

   - name: daemon reload and start # ansible demon module
     ansible.builtin.systemd_service:
      daemon_reload: true

   - name: start and enable cart
     ansible.builtin.service:
      name: cart 
      state: restarted
      enabled: yes  


  
 
