- name: catalogue
  hosts: catalogue
  become: yes
  tasks: 
   - name: disable old nodejs and enable nodejs
     ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

   - name: Install nodejs # ansible install nodejs module
     ansible.builtin.dnf:
      name: nodejs
      state: present

   - name: Add user roboshop # ansible adduseer module
     ansible.builtin.user:
      name: roboshop 

   - name: Recursively remove app directory # ansible app directory
     ansible.builtin.file:
      path: /app
      state: directory    

   - name: Download for catalogue application # ansible download module
     ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

   - name: extract catalogue application # ansible unarchive module
     ansible.builtin.copy:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

   - name: Install dependencies #shell command faster than ansible
     ansible.builtin.command: npm install
     args:
       chdir: /app

  #  - name: Copy catalogue service # ansible copy module
  #    ansible.builtin.copy:
  #     src: catalogue.service
  #     dest: /etc/systemd/system/catalogue.service

  #  - name: daemon reload and start # ansible demon module
  #    ansible.builtin.systemd_service:
  #     daemon_reload: true

  #   # let's start after the data is loaded

  #  - name: Copy mongodb repo # ansible copy module
  #    ansible.builtin.copy:
  #     src: mongodb.repo
  #     dest: /etc/yum.repos.d/mongo.repo

  #  - name: Install mongodb # ansible install package 
  #    ansible.builtin.package:
  #     name: mongodb-org-shell
  #     state: present       
       

 
