- name: catalogue
  hosts: catalogue
  become: yes
  tasks: 
   - name: disable old nodejs and enable nodejs
     ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

   - name: Install nodejs # ansible install nodejs module
     ansible.builtin.dnf:
      name: nodejs
      state: present

   - name: Add user roboshop # ansible adduseer module
     ansible.builtin.user:
      name: roboshop 

   - name: Recursively remove app directory # ansible app directory
     ansible.builtin.file:
      path: /app
      state: absent  

   - name: Download for catalogue application # ansible download module
     ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

   - name: extract catalogue application
     ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes 
